---
name: Build & deploy to environment

#
# Build the docker image, and deploy it to the given environment.
#

on:
  workflow_call:
    # Depends on the following vars
    # - CONTAINER_PLATFORMS
    # - CONTAINER_REGISTRY_ENDPOINT
    # - K8S_CLUSTER_ID
    # - K8S_DEPLOYMENTS
    # - K8S_LABELS
    # - K8S_NAMESPACE
    # - RUNNER_DEFAULT
    # - RUNNER_INFRA
    # For Azure vendor:
    # - AZURE_RESOURCE_GROUP
    # For DigitalOcean vendor:
    # For Scaleway vendor:
    # - SCALEWAY_ORGANIZATION_ID
    # - SCALEWAY_PROJECT_ID
    # - SCALEWAY_REGION
    inputs:
      vendor:
        description: The vendor to communicate with (azure, digitalocean, scaleway)
        type: string
        required: true
      environment:
        description: Target environment to deploy to
        type: string
        required: true
      image:
        description: Image name (fallback to repository name)
        type: string
        required: false
      image-variants:
        description: List of variants to build (folders in monorepo, separated by commas)
        type: string
        required: false
    secrets:
      # Vendor: Azure
      AZURE_CLIENT_ID:
        description: Azure client ID for login with an Azure service principal
        required: false
      AZURE_TENANT_ID:
        description: Azure tenant ID for login with an Azure service principal
        required: false
      AZURE_SUBSCRIPTION_ID:
        description: Azure subscription ID for login with an Azure service principal
        required: false
      AZURE_CR_USER:
        description: Azure container registry user
        required: false
      AZURE_CR_TOKEN:
        description: Azure container registry token
        required: false
      # Vendor: DigitalOcean
      DIGITALOCEAN_API_USER:
        description: DigitalOcean user email
        required: false
      DIGITALOCEAN_API_TOKEN:
        description: DigitalOcean API token
        required: false
      # Vendor: Scaleway
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: false
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: false

jobs:
  validate-and-generate-matrix:
    name: Validate inputs & generate build matrix
    runs-on: ${{ vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    outputs:
      variants: ${{ steps.gen-matrix.outputs.variants }}
    steps:
      - name: Validate & generate docker workflow inputs
        id: gen-matrix
        uses: wisemen-digital/devops-github-actions/.github/actions/docker/validate-and-generate-inputs@v1
        with:
          vendor: ${{ inputs.vendor }}
          image-variants: ${{ inputs.image-variants }}
          # Vendor: azure
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-user: ${{ secrets.AZURE_CR_USER }}
          azure-token: ${{ secrets.AZURE_CR_TOKEN }}
          # Vendor: digitalocean
          digitalocean-user: ${{ secrets.DIGITALOCEAN_API_USER }}
          digitalocean-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          # Vendor: scaleway
          scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}

  build-and-deploy:
    name: Build & Deploy ${{ matrix.variant.path }} to ${{ inputs.environment }}
    needs: [validate-and-generate-matrix]
    if: ${{ needs.validate-and-generate-matrix.outputs.variants != '[]' }}
    strategy:
      matrix:
        variant: ${{ fromJson(needs.validate-and-generate-matrix.outputs.variants) }}
    runs-on: ${{ vars.RUNNER_INFRA || 'ubuntu-latest' }}
    environment: ${{ inputs.environment }}
    steps:
      # Setup
      - name: Setup Docker environment
        id: setup
        uses: wisemen-digital/devops-github-actions/.github/actions/docker/setup@v1
        with:
          vendor: ${{ inputs.vendor }}
          container-registry: ${{ vars.CONTAINER_REGISTRY_ENDPOINT }}
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ inputs.image }}
          k8s-labels: ${{ vars.K8S_LABELS }}
          prepare-for-building: true
          variant-path: ${{ matrix.variant.path }}
          # Vendor: azure
          azure-user: ${{ secrets.AZURE_CR_USER }}
          azure-token: ${{ secrets.AZURE_CR_TOKEN }}
          # Vendor: digitalocean
          digitalocean-user: ${{ secrets.DIGITALOCEAN_API_USER }}
          digitalocean-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          # Vendor: scaleway
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
      - name: Calculate image metadata
        run: |
          image_ref="${{ steps.setup.outputs.registry }}/${{ steps.setup.outputs.image }}"
          echo "tags=`echo '${{ inputs.environment || github.ref_name }}' | \
            sed "s#/#_#g;s#[^,]*#${image_ref}:&#g"`" >> "$GITHUB_ENV"
          echo "timestamp=`date +'%Y-%m-%dT%H:%M:%S'`" >> "$GITHUB_ENV"
      # Build
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ vars.CONTAINER_PLATFORMS || 'linux/amd64' }}
          push: true
          tags: ${{ env.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ matrix.variant.path }}
          build-args: |
            BUILD_COMMIT=${{ github.sha }}
            BUILD_NUMBER=${{ github.run_number }}
            BUILD_TIMESTAMP=${{ env.timestamp }}
      # Rollout
      - name: Rollout on cluster
        uses: wisemen-digital/devops-github-actions/.github/actions/infra/k8s/rollout@v1
        with:
          vendor: ${{ inputs.vendor }}
          cluster-id: ${{ vars.K8S_CLUSTER_ID }}
          rollout-deployments: ${{ vars.K8S_DEPLOYMENTS }}
          rollout-labels: ${{ steps.setup.outputs.k8s-labels }}
          rollout-namespace: ${{ vars.K8S_NAMESPACE }}
          # Vendor: azure
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          # Vendor: digitalocean
          digitalocean-api-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          # Vendor: scaleway
          scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          scaleway-organization-id: ${{ vars.SCALEWAY_ORGANIZATION_ID }}
          scaleway-project-id: ${{ vars.SCALEWAY_PROJECT_ID }}
          scaleway-region: ${{ vars.SCALEWAY_REGION }}
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
