---
name: Build & Push Docker

#
# Build the application's Dockerfile, and push it to the given registry.
#
# Some notes:
# - Will fallback to docker hub registry (if none is provided)
# - Image name will default to the current repository name
# - Tag will default to the current branch
#

on:  # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      container-registry:
        description: Container registry endpoint (fallback to Docker Hub)
        required: false
        type: string
      image:
        description: Image name (fallback to repository name)
        required: false
        type: string
      tag:
        description: Image tag (fallback to branch name)
        required: false
        type: string
    secrets:
      CONTAINER_REGISTRY_USERNAME:
        description: Container registry username ('nologin' for Scaleway)
        required: true
      CONTAINER_REGISTRY_PASSWORD:
        description: Container registry password (secret key for Scaleway)
        required: true
    outputs:
      digest:
        description: Result image digest
        value: ${{ jobs.build-and-push.outputs.digest }}
      manifest:
        description: Image manifest (registry + image + tag)
        value: ${{ jobs.build-and-push.outputs.manifest }}

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      manifest: ${{ env.container_registry }}/${{ env.image }}:${{ env.tag }}
    steps:
      - name: Prepare environment
        run: |
          echo "container_registry=${{ inputs.container-registry || 'docker.io' }}" >> "$GITHUB_ENV"
          echo "image=`basename ${{ inputs.image || github.repository }}`" >> "$GITHUB_ENV"
          echo "tag=`echo '${{ inputs.tag || github.ref_name }}' | sed 's/\//_/g'`" >> "$GITHUB_ENV"
          echo "timestamp=`date +'%Y-%m-%dT%H:%M:%S'`" >> "$GITHUB_ENV"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to custom registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.container_registry }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.container_registry }}/${{ env.image }}:${{ env.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_COMMIT=${{ github.sha }}
            BUILD_NUMBER=${{ github.run_number }}
            BUILD_TIMESTAMP=${{ env.timestamp }}
