---
name: Rollout deployments (vendor agnostic)

#
# Check what's changed (via filters, or provide your own list) and roll it out.
#

on:
  workflow_call:
    # Depends on the following vars
    # - K8S_CLUSTER_ID
    # - RUNNER_DEFAULT
    # - RUNNER_INFRA
    # For Azure vendor:
    # - AZURE_RESOURCE_GROUP
    # For DigitalOcean vendor:
    # For Scaleway vendor:
    # - SCALEWAY_ORGANIZATION_ID
    # - SCALEWAY_PROJECT_ID
    # - SCALEWAY_REGION
    inputs:
      vendor:
        description: The vendor to communicate with (azure, digitalocean, scaleway)
        type: string
        required: true
      cluster-deployments:
        description: List of deployments to roll out (folders), separated by commas
        required: true
        type: string
    secrets:
      K8S_MODULES_SECRET:
        description: Token to access github modules repositories
        required: true
      # Vendor: Azure
      AZURE_CLIENT_ID:
        description: Azure client ID for login with an Azure service principal
        required: false
      AZURE_TENANT_ID:
        description: Azure tenant ID for login with an Azure service principal
        required: false
      AZURE_SUBSCRIPTION_ID:
        description: Azure subscription ID for login with an Azure service principal
        required: false
      # Vendor: DigitalOcean
      DIGITALOCEAN_API_TOKEN:
        description: DigitalOcean API token
        required: false
      # Vendor: Scaleway
      SCALEWAY_ACCESS_KEY:
        description: Scaleway API key ID
        required: false
      SCALEWAY_SECRET_KEY:
        description: Scaleway API key secret
        required: false

jobs:
  generate-matrix:
    name: Generate job matrices
    runs-on: ${{ vars.RUNNER_DEFAULT || 'ubuntu-latest' }}
    outputs:
      deployments: ${{ steps.changed-paths-filter.outputs.matrix }}
    steps:
      - name: Generate Matrix
        id: changed-paths-filter
        uses: wisemen-digital/devops-ga-changed-paths-filter@main
        with:
          filter-file: .github/k8s-rollout-filters.yaml
          changes-override: ${{ inputs.cluster-deployments }}

  rollout-to-k8s:
    name: Rollout to k8s
    needs: [generate-matrix]
    strategy:
      matrix:
        deployment: ${{ fromJson(needs.generate-matrix.outputs.deployments) }}
    if: ${{ needs.generate-matrix.outputs.deployments != '[]' }}
    runs-on: self-hosted
    environment: ${{ matrix.deployment.environment }}
    steps:
      - name: Apply Configuration
        uses: wisemen-digital/devops-github-actions/.github/actions/infra/k8s/apply@feature/azure-deployments
        with:
          vendor: ${{ inputs.vendor }}
          cluster-id: ${{ vars.K8S_CLUSTER_ID }}
          config-path: ${{ matrix.deployment.path }}
          github-access-token: ${{ secrets.K8S_MODULES_SECRET }}
          # Vendor: azure
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure-resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          # Vendor: digitalocean
          digitalocean-api-token: ${{ secrets.DIGITALOCEAN_API_TOKEN }}
          # Vendor: scaleway
          scaleway-access-key: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          scaleway-organization-id: ${{ vars.SCALEWAY_ORGANIZATION_ID }}
          scaleway-project-id: ${{ vars.SCALEWAY_PROJECT_ID }}
          scaleway-region: ${{ vars.SCALEWAY_REGION }}
          scaleway-secret-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
