---
name: Rollout object storage (DigitalOcean)

#
# Check what's changed (via filters, or provide your own list) and roll it out.
#

on:
  workflow_call:
    # Depends on the following vars
    # - DIGITALOCEAN_REGION
    inputs:
      # bucket info
      bucket-deployments:
        description: List of deployments to roll out (folders), separated by commas
        required: false
        type: string
    secrets:
      DIGITALOCEAN_ACCESS_KEY:
        description: DigitalOcean API key ID
        required: true
      DIGITALOCEAN_SECRET_KEY:
        description: DigitalOcean API key secret
        required: true

jobs:
  deprecation-warning:
    name: Deprecation message
    runs-on: ubuntu-latest
    steps:
      - name: Deprecation message
        run: |
          echo "::warning file=.github/workflows/rollout-to-s3.yml,line=20::\
          Deprecated workflow, switch to vendor agnostic workflow."

  rollout-to-s3:
    uses: wisemen-digital/devops-github-actions/.github/workflows/infra-s3-rollout.yml@main
    with:
      vendor: digitalocean
      bucket-deployments: ${{ inputs.bucket-deployments }}
    secrets: inherit
